# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers # wallpaper directory
$lock = $scriptsDir/LockScreen.sh # lock screen script
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh # wallpaper change script
$livewallpaper=""

# Wallpaper 
exec-once = swww-daemon --format xrgb # start wallpaper agent
#exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper # mpv paper for gif or mp4 wallpapers
exec-once = $SwwwRandom $wallDIR # wallpaper change every 30 minutes

# Startup (DONT TOUCH)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit (Polkit Gnome / KDE)
exec-once = $scriptsDir/Polkit.sh # start polkit agent (necessary for sudo related things)

# Default Startup Apps
exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 30 # set cursor and size
exec-once = nm-applet --indicator # start network manager tray icon
exec-once = blueman-applet # start bluetooth manager tray icon
exec-once = swaync # start notification center
#exec-once = waybar # start wayland bar (top bar)
exec-once = $UserScripts/LaunchWaybar.sh # custom script that restarts waybar on config change

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Rainbow Borders
exec-once = $UserScripts/RainbowBorders.sh

# Starting Hypridle to start Hyprlock
exec-once = hypridle

#############################################################################################################
# Damieon Startup # Damieon Startup # Damieon Startup # Damieon Startup # Damieon Startup # Damieon Startup #
#############################################################################################################

# hyprland utilities
exec-once = hyprsunset

# osu! 
exec-once = otd-daemon # start opentabletdriver
exec-once = osumem # start cosu-trainer reader

# discord
exec-once = discover-overlay # start discord overlay

# audio
exec-once = easyeffects --gapplication-service # start headphone/mic equalizer
#exec-once = mpd # start music player daemon
#exec-once = sleep 1 && mpd-mpris # start music player daemon mpris wrapper
#exec-once = sleep 1 && mpd-discord-rpc # start music player daemon discord integration

# mouse
#exec-once = sleep 2 && polychromatic-tray-applet # start razer tray icon

