sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/paru.git && cd paru && makepkg -si && cd ~ && yay -S --needed --noconfirm gvfs thunar-archive-plugin thunar-media-tags-plugin thunar-volman \
        mesa lib33-mesa vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader lact \
        java-environment-common java-runtime-common jdk17-openjdk jq jre-openjdk jre8-openjdk jre8-openjdk-headless \
        adwsteamgtk appimagelauncher protonplus polkit-gnome gnome-disk-utility xorg-xhost snapper btrfs-assistant uwsm fzf mpv fastanime fish fisher firefox vim cron hyprfreeze-git hyprpicker \
        aic95xx-firmware ast-firmware linux-firmware-qlogic linux-firmware-bnx2x linux-firmware-liquidio power-profiles-daemon linux-firmware-mellanox linux-firmware-nfp wd719x-firmware upd72020x-fw \
        steam lutris wine winetricks gamemode lib33-gamemode giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls mpg123 lib32-mpg123 openal lib32-openal v4l-utils \
        lib33-v4l-utils libgpg-error lib32-libgpg-error alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo sqlite lib32-sqlite libxcomposite lib32-libxcomposite \
        libxinerama lib33-libxinerama ncurses lib32-ncurses opencl-icd-loader lib32-opencl-icd-loader libxslt lib32-libxslt libva lib32-libva gtk3 lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs \
        vulkan-icd-loader lib33-vulkan-icd-loader obs-studio vesktop-electron-git mangohud lib32-mangohud goverlay gamescope bluez bluez-utils lib32-libpulse pipewire pipewire-pulse pipewire-alsa linux-headers xwaylandvideobridge \
        polychromatic openrazer-daemon opentabletdriver cosu-trainer-bin transmission-gtk mpd mpd-mpris rmpc \
        pamac-all networkmanager greetd nwg-hello && sudo usermod -aG gamemode damieon && sudo systemctl enable fstrim.timer && sudo systemctl enable NetworkManager.service && sudo systemctl enable greetd.service && sudo systemctl enable bluetooth.service && sudo systemctl enable cronie.service && sudo modprobe razermouse && sudo gpasswd -a $USER plugdev && sudo systemctl enable --now lactd && echo /usr/bin/fish | sudo tee -a /etc/shells && chsh -s /usr/bin/fish && fish
