color0 #424849
color1 #ffb4ab
color2 #b7cace
color3 #c1c8c9
color4 #cdc3d5
color5 #b7cace
color6 #c1c8c9
color7 #e4e2e2
color8 #8c9293
color9 #ffb4ab
color10 #b7cace
color11 #c1c8c9
color12 #cdc3d5
color13 #b7cace
color14 #c1c8c9
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c2c7c9
selection_background  #424849
active_border_color   #b7cace
inactive_border_color #424849
url_color             #b7cace

active_tab_foreground   #223337
active_tab_background   #b7cace
inactive_tab_foreground #c2c7c9
inactive_tab_background #424849
cursor_trail_color      #c2c7c9
