color0 #5b403b
color1 #ffb4ab
color2 #ffb4a4
color3 #ffb4a4
color4 #f1bf5b
color5 #ffb4a4
color6 #ffb4a4
color7 #f9dcd6
color8 #aa8982
color9 #ffb4ab
color10 #ffb4a4
color11 #ffb4a4
color12 #f1bf5b
color13 #ffb4a4
color14 #ffb4a4
color15 #f9dcd6

cursor                #f9dcd6
cursor_text_color     #1e100d
background            #1e100d
foreground            #f9dcd6
selection_foreground  #e3beb6
selection_background  #5b403b
active_border_color   #ffb4a4
inactive_border_color #5b403b
url_color             #ffb4a4

active_tab_foreground   #640c00
active_tab_background   #ffb4a4
inactive_tab_foreground #e3beb6
inactive_tab_background #5b403b
cursor_trail_color      #e3beb6
