# Force low latency for MOTU M2
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.*MOTU.*"
      }
      {
        node.name = "~alsa_output.*MOTU.*"
      }
    ]
    actions = {
      update-props = {
        node.latency = 32/48000
        api.alsa.period-size = 32
      }
    }
  }
]
