# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F7E2E2
background         #00000A
cursor             #B2ABB7

active_tab_foreground     #00000A
active_tab_background     #F7E2E2
inactive_tab_foreground   #F7E2E2
inactive_tab_background   #00000A

active_border_color   #F7E2E2
inactive_border_color #00000A
bell_border_color     #1E2E43

color0      #00000A
color1		#1E2E43
color2		#525769
color3		#6C6B7C
color4		#6C6B7C
color5		#6C6B7C
color6		#AE8280
color7		#EBCECD
color8		#A5908F
color9		#283D59
color10		#6D748C
color11		#908FA5
color12		#908FA5
color13		#908FA5
color14		#E8ADAB
color15		#EBCECD
