color0 #444657
color1 #ffb4ab
color2 #bbc3ff
color3 #bbc3ff
color4 #f3aeff
color5 #bbc3ff
color6 #bbc3ff
color7 #e2e1f0
color8 #8e8fa3
color9 #ffb4ab
color10 #bbc3ff
color11 #bbc3ff
color12 #f3aeff
color13 #bbc3ff
color14 #bbc3ff
color15 #e2e1f0

cursor                #e2e1f0
cursor_text_color     #11131d
background            #11131d
foreground            #e2e1f0
selection_foreground  #c4c5da
selection_background  #444657
active_border_color   #bbc3ff
inactive_border_color #444657
url_color             #bbc3ff

active_tab_foreground   #001b97
active_tab_background   #bbc3ff
inactive_tab_foreground #c4c5da
inactive_tab_background #444657
cursor_trail_color      #c4c5da
