-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "28")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        blur = {
            enabled = true,
            passes = 3,
            size = 6,
            vibrancy_darkness = 0.06,
            xray = false,
        },
        dim_inactive = true,
        rounding_power = 3.0,
        shadow = {
            offset = "0 0",
            range = 30,
            render_power = 4,
        },
    },
    general = {
        gaps_in = 10,
        gaps_out = 15,
    },
})

-- Bezier curves
hl.curve("quart", { type = "bezier", points = { {0.25, 1.0}, {0.5, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
})
hl.animation({
    leaf = "borderangle",
    enabled = false,
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6.0,
    bezier = "quart",
    style = "slide",
})
