-- Generated by nwg-displays on 2026-06-27 at 20:57:33. Do not edit manually.

hl.monitor({
    output = "DP-3",
    mode = "2560x1440@240.0",
    position = "810x0",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.33,
    bitdepth = 10,
    transform = 1
})
