context.modules = [
    {   name = libpipewire-module-filter-chain
        args = {
            node.description = "MOTU M2 Mono Mic"
            media.name       = "MOTU M2 Mono Mic"
            filter.graph = {
                nodes = [
                    { name = dup  type = builtin label = copy }
                    { name = outL type = builtin label = copy }
                    { name = outR type = builtin label = copy }
                ]
                links = [
                    { output = "dup:Out"  input = "outL:In" }
                    { output = "dup:Out"  input = "outR:In" }
                ]
                inputs  = [ "dup:In" ]
                outputs = [ "outL:Out" "outR:Out" ]
            }
            capture.props = {
                node.name         = "alsa_input.usb-MOTU_M2_M2MA0614IC-00.pro-input-0"
                audio.position    = [ AUX0 ]
                stream.dont-remix = true
                node.passive      = true
            }
            playback.props = {
                node.name         = "motu-mono-mic"
                node.description  = "MOTU M2 Mono Mic"
                audio.position    = [ AUX0 AUX1 ]
                media.class       = "Audio/Source"
            }
        }
    }
]
